db/seeds.rb
=> testing branch

Gemfile, Gemfile.lock, app/controllers/bookings_controller.rb, app/controllers/cars_controller.rb, app/models/booking.rb, app/models/car.rb, app/models/user.rb, config/initializers/devise.rb, config/locales/devise.en.yml, config/routes.rb, db/migrate/20240702190143_create_cars.rb, db/migrate/20240702190707_create_bookings.rb, db/migrate/20240702192014_devise_create_users.rb, db/migrate/20240703164113_add_user_and_car_to_bookings.rb, db/migrate/20240703164222_add_user_to_cars.rb, db/schema.rb, test/controllers/bookings_controller_test.rb, test/controllers/cars_controller_test.rb, test/models/booking_test.rb, test/models/car_test.rb, test/models/user_test.rb
Added models for car and bookings. Used devise to create a user model. Added routes and controllers. Have just started to add functionality to cars controller.
=> added models, schema, routes and controllers

app/controllers/cars_controller.rb, db/migrate/20240704134122_add_price_to_cars.rb, db/schema.rb
Created actions in controller and added price to the cars model. Also made the files for cars view
=> Schema and car model

db/migrate/20240704134122_add_price_to_cars.rb, db/migrate/20240704184412_add_price_to_cars.rb, db/migrate/20240704185804_add_price_to_cars.rb
=> Fix Migration Issue

app/assets/stylesheets/pages/_index.scss, app/controllers/cars_controller.rb, app/models/user.rb, app/views/cars/index.html.erb, app/views/layouts/application.html.erb, db/migrate/20240704184022_add_description_to_cars.rb, db/migrate/20240705130931_add_username_to_users.rb, db/schema.rb, db/seeds.rb
Changed the index.html.erb file, added to the scss file. Populated the DB with records of the User and Car model. Also changed the schema to add a username table to the User model
=> Html css js

app/views/cars/index.html.erb
Added a link from cars on the index page to their show page
=> added a link on the cars from the index to the show page

db/migrate/20240702192014_devise_create_users.rb, db/migrate/20240705130931_add_username_to_users.rb
migration restored to allow users
=> migration restored to allow users

app/assets/stylesheets/pages/_home.scss, app/views/pages/home.html.erb, db/schema.rb
created the home page css and html
=> home page created

app/assets/stylesheets/application.scss, app/views/layouts/application.html.erb, app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb
Changes navbar location to a new partial
=> navbar partial

app/assets/stylesheets/pages/_home.scss, app/views/cars/show.html.erb, app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb, config/initializers/simple_form.rb, config/initializers/simple_form_bootstrap.rb
made links on the navbar and applied css to the car on show page
=> created links

app/controllers/bookings_controller.rb, app/views/bookings/confirmation.html.erb, app/views/bookings/index.html.erb, app/views/bookings/new.html.erb, app/views/cars/_form.html.erb, app/views/cars/index.html.erb, config/routes.rb, db/schema.rb, db/seeds.rb
=> Bookings implementatio

app/assets/stylesheets/pages/_home.scss
made changes to home-page. I change the colour of the log
=> made changes to home-page

app/controllers/bookings_controller.rb
=> Confirmation

app/views/pages/home.html.erb
changed the button colour as a different colour as before. Just checking if its the same
=> changed the button colour

app/views/bookings/show.html.erb
Changed a typo in the bookings show page
=> cleaned up bookings show page

app/assets/stylesheets/pages/_home.scss, app/views/cars/index.html.erb
made images the same size
changed header
added background color
added price to bottom of image
=> index page images

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/pages/_home.scss, app/models/car.rb, app/views/cars/new.html.erb, app/views/shared/_navbar.html.erb
Branch name is deceptive, actually just did a link to the new car view
=> created the car_new view and added a link from the navbar

app/views/bookings/_booking.html.erb, app/views/bookings/index.html.erb, app/views/shared/_navbar.html.erb, app/views/users/show.html.erb
I've implement the nav-bar with bookings where new bookings are visible.
=> Booking Implementation

app/assets/stylesheets/components/_navbar.scss, app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb
=> profile-icon

app/assets/stylesheets/pages/_home.scss, app/views/cars/index.html.erb, app/views/layouts/application.html.erb
the new car link on the bottom was just a blue hyperlink
I've changed this to a button
Used the same colour as the button on the homepage but can be changed
=> formatted button to match style

app/controllers/bookings_controller.rb, app/views/bookings/index.html.erb, app/views/bookings/show.html.erb
I've implement the Bookings Index.
=> bookings page

app/assets/stylesheets/pages/_home.scss
changed the button search in the home page that shows the images
=> home button updated the css

app/assets/stylesheets/pages/_home.scss, app/views/cars/new.html.erb, app/views/shared/_navbar.html.erb
Edited the form and added back button
=> edited new car form layout

app/assets/stylesheets/pages/_home.scss, app/controllers/bookings_controller.rb, app/controllers/cars_controller.rb, app/models/car.rb, app/views/bookings/index.html.erb
Have made significant but unfinished changes to the bookings page
=> Bookings styling

app/assets/stylesheets/pages/_home.scss, app/views/cars/show.html.erb, app/views/shared/_navbar.html.erb
Changed the show page  and the lay out of it so the images look similar and not as big as before. changed the buttons to look similar with the rest of the pages.
=> changed the layout of the show page

app/assets/stylesheets/pages/_home.scss, app/views/cars/index.html.erb
Cars Listing page implemented.
=> Cars Index

app/assets/stylesheets/pages/_home.scss
Put the margin back in the header box
=> put margin back

app/assets/stylesheets/pages/_home.scss, app/views/cars/show.html.erb
=> updated the images size

app/assets/stylesheets/pages/_home.scss, app/views/cars/index.html.erb
Added gradient to header box
Changed image sizes on index and added shadow
=> index page changed

app/assets/stylesheets/pages/_home.scss
Curved the button that was square
=> curved button

app/assets/stylesheets/pages/_home.scss, app/views/cars/index.html.erb
search bar on the index page aligned with the button
=> search bar on the index page aligned with the button

app/assets/stylesheets/pages/_home.scss, app/views/cars/index.html.erb
Added padding to button on bottom
=> styled index page
